package com.animetracker.service;

import org.springframework.stereotype.Service;

/**
 * Vector utility service.
 *
 * External paid embedding API calls were intentionally removed from the app.
 * Semantic embedding is now generated by the local ML sidecar custom model.
 */
@Service
public class EmbeddingService {

    /**
     * Disabled by design: no external paid embedding fallback.
     */
    public float[] embed(String text) {
        throw new IllegalStateException(
                "External embedding API calls are disabled. Use ML sidecar custom embeddings.");
    }

    /**
     * Convert a float[] embedding to the string format pgvector expects: "[0.1,0.2,...]".
     */
    public static String toVectorString(float[] embedding) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < embedding.length; i++) {
            if (i > 0) {
                sb.append(",");
            }
            sb.append(embedding[i]);
        }
        sb.append("]");
        return sb.toString();
    }

    /**
     * Parse a pgvector string like "[0.1,0.2,...]" back to float[].
     */
    public static float[] fromVectorString(String vectorStr) {
        String inner = vectorStr.substring(1, vectorStr.length() - 1);
        String[] parts = inner.split(",");
        float[] result = new float[parts.length];
        for (int i = 0; i < parts.length; i++) {
            result[i] = Float.parseFloat(parts[i].trim());
        }
        return result;
    }
}

